#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 11 10:44:29 CDT 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim dut_top_tb_behav -key {Behavioral:sim_1:Functional:dut_top_tb} -tclbatch dut_top_tb.tcl -view /home/bangya/BOOM_on_HTG937/dut_top_tb_behav.wcfg -log simulate.log"
xsim dut_top_tb_behav -key {Behavioral:sim_1:Functional:dut_top_tb} -tclbatch dut_top_tb.tcl -view /home/bangya/BOOM_on_HTG937/dut_top_tb_behav.wcfg -log simulate.log

